#!/bin/bash
liczba=`python -c "import random; print random.randrange(1,50);"`
echo "$liczba"
echo "podaj liczbe od 1 do 50"
read l
if [ "$l" -gt "$liczba" ]; then
echo "za duzo"
fi
if [ "$l" -lt "$liczba" ]; then
echo "za malo"
fi
if [ "$l" == "$liczba" ]; then
echo "Ok"
fi
