#!/bin/bash
echo -n "podaj liczbe klientow: "
read klienci
echo "najwiekszy przelew:"
./genlogs.sh $klienci | grep amount | sed -e 's/[a-z]*//g' | cut -c 63-101 | sed -e 's/( : .*)//g' -e 's/ //g' | sort | sort -n | tail -1


